name: frecos
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
      - numpy
      - matplotlib
      - cachetools
      - requests
      - pytest
      - pytest-benchmark
      - flake8
      - psutil
